# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 400)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setSizeGripEnabled(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_master = QtWidgets.QVBoxLayout()
        self.verticalLayout_master.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_master.setObjectName("verticalLayout_master")
        self.label_prompt = QtWidgets.QLabel(parent=Dialog)
        self.label_prompt.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_prompt.setObjectName("label_prompt")
        self.verticalLayout_master.addWidget(self.label_prompt)
        self.horizontalLayout_input = QtWidgets.QHBoxLayout()
        self.horizontalLayout_input.setObjectName("horizontalLayout_input")
        self.text_field = QtWidgets.QPlainTextEdit(parent=Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_field.sizePolicy().hasHeightForWidth())
        self.text_field.setSizePolicy(sizePolicy)
        self.text_field.setObjectName("text_field")
        self.horizontalLayout_input.addWidget(self.text_field)
        self.button_enter = QtWidgets.QPushButton(parent=Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_enter.sizePolicy().hasHeightForWidth())
        self.button_enter.setSizePolicy(sizePolicy)
        self.button_enter.setObjectName("button_enter")
        self.horizontalLayout_input.addWidget(self.button_enter)
        self.verticalLayout_master.addLayout(self.horizontalLayout_input)
        self.label_text_validation = QtWidgets.QLabel(parent=Dialog)
        self.label_text_validation.setObjectName("label_text_validation")
        self.verticalLayout_master.addWidget(self.label_text_validation)
        self.label_student_count = QtWidgets.QLabel(parent=Dialog)
        self.label_student_count.setObjectName("label_student_count")
        self.verticalLayout_master.addWidget(self.label_student_count)
        self.label_student_scores = QtWidgets.QLabel(parent=Dialog)
        self.label_student_scores.setObjectName("label_student_scores")
        self.verticalLayout_master.addWidget(self.label_student_scores)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.button_reset = QtWidgets.QPushButton(parent=Dialog)
        self.button_reset.setObjectName("button_reset")
        self.horizontalLayout_2.addWidget(self.button_reset)
        self.button_quit = QtWidgets.QPushButton(parent=Dialog)
        self.button_quit.setObjectName("button_quit")
        self.horizontalLayout_2.addWidget(self.button_quit)
        self.verticalLayout_master.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.verticalLayout_master)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_prompt.setText(_translate("Dialog", "Prompt text"))
        self.button_enter.setText(_translate("Dialog", "Enter"))
        self.label_text_validation.setText(_translate("Dialog", "Valid input accepted!"))
        self.label_student_count.setText(_translate("Dialog", "Number of Students: <b>X</b>"))
        self.label_student_scores.setText(_translate("Dialog", "Student Scores:\n"
"Student 1 - XX\n"
"Student 2 - XX\n"
"Student 3 - XX"))
        self.button_reset.setText(_translate("Dialog", "Reset"))
        self.button_quit.setText(_translate("Dialog", "Quit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
